# SPDX-License-Identifier: BSD-2-Clause
# Cargo.toml for libcoap
# This file is part of the libcoap-rs crate, see the README and LICENSE files for
# more information and terms of use.
# Copyright © 2021-2023 The NAMIB Project Developers, all rights reserved.

[package]
name = "libcoap-rs"
description = "An idiomatic wrapper around the libcoap CoAP library for Rust."
version = "0.2.2"
edition = "2021"
license = "BSD-2-Clause"
readme = "README.md"
repository = "https://github.com/namib-project/libcoap-rs"
authors = ["Hugo Hakim Damer <hdamer@uni-bremen.de>"]
categories = ["api-bindings", "network-programming", "embedded"]
keywords = ["coap", "libcoap"]

[features]
default = ["dtls"]                                    #, "tcp"]                             # "dtls_openssl"]
dtls = ["libcoap-sys/dtls"]
dtls_tinydtls = ["libcoap-sys/dtls_backend_tinydtls"]
dtls_openssl = ["libcoap-sys/dtls_backend_openssl"]
dtls_gnutls = ["libcoap-sys/dtls_backend_gnutls"]
dtls_mbedtls = ["libcoap-sys/dtls_backend_mbedtls"]
tcp = []
nightly = []
vendored = ["libcoap-sys/vendored"]

[dependencies]
libcoap-sys = { version = "^0.2.2", path = "../libcoap-sys" }
libc = { version = "^0.2" }
num-derive = { version = "^0.4" }
num-traits = { version = "^0.2" }
url = { version = "^2.2" }
rand = { version = "^0.8.4" }
thiserror = "^1.0"

[package.metadata.docs.rs]
features = ["dtls", "dtls_openssl", "vendored"]
